/* ===================================================
   EQUIPO MATERO — products-data.js
   Datos compartidos entre la tienda y el admin.
   NO modificar manualmente — usar el panel de admin.
   =================================================== */

const defaultProducts = [
  { id:1,  category:'imperiales',  categoryLabel:'Imperial',   name:'Imperial Alpaca Liso',         variant:'Cuero Negro',      details:['Imperial de Calabaza','Forrado en Cuero Liso Negro','Virola de Alpaca Lisa'],          price:35000, image:'images/Imperial_Alpaca_Liso.png',              featured:false },
  { id:2,  category:'imperiales',  categoryLabel:'Imperial',   name:'Imperial Alpaca Lisa',         variant:'Cuero Borravino',  details:['Imperial de Calabaza','Forrado en Cuero Liso Borravino','Virola de Alpaca Lisa'],       price:35000, image:'images/Imperial_Alpaca_Lisa.png',              featured:false },
  { id:3,  category:'imperiales',  categoryLabel:'Imperial',   name:'Imperial Premium',             variant:'Cuero Crudo',      details:['Imperial de Calabaza','Forrado en Cuero Crudo','Virola de Alpaca Lisa'],                price:55000, image:'images/Imperial_Premium.png',                  featured:true  },
  { id:4,  category:'imperiales',  categoryLabel:'Imperial',   name:'Imperial Algarrobo',           variant:'',                 details:['Imperial de Algarrobo','Virola de Alpaca'],                                             price:29000, image:'images/Imperial_Algarrobo.png',                featured:false },
  { id:5,  category:'torpedos',    categoryLabel:'Torpedo',    name:'Torpedo Cincelado',            variant:'Cuero Negro',      details:['Torpedo de Calabaza','Forrado en Cuero Liso Negro','Virola de Alpaca Cincelada'],       price:35000, image:'images/Torpedo_Cincelado_Negro.png',            featured:false },
  { id:6,  category:'torpedos',    categoryLabel:'Torpedo',    name:'Torpedo Cincelado',            variant:'Cuero Borravino',  details:['Torpedo de Calabaza','Forrado en Cuero Liso Borravino','Virola de Alpaca Cincelada'],  price:35000, image:'images/Torpedo_Cincelado_Borravino.png',       featured:false },
  { id:7,  category:'torpedos',    categoryLabel:'Torpedo',    name:'Torpedo Premium',              variant:'Cuero Crudo',      details:['Torpedo de Calabaza','Forrado en Cuero Crudo','Virola de Alpaca Cincelada'],            price:55000, image:'images/Torpedo_Premium.png',                   featured:true  },
  { id:8,  category:'torpedos',    categoryLabel:'Torpedo',    name:'Torpedo Rey',                  variant:'',                 details:['Torpedo de Algarrobo','Virola de Alpaca Cincelada','2 Aros de Bronce'],                 price:38000, image:'images/Torpedo_Rey.png',                       featured:false },
  { id:9,  category:'camioneros',  categoryLabel:'Camionero',  name:'Camionero Acero Liso',         variant:'Cuero Negro',      details:['Camionero de Calabaza','Forrado en Cuero Liso Negro','Virola de Acero Lisa'],           price:26500, image:'images/Camionero_Acero_Liso_Negro.png',        featured:false },
  { id:10, category:'camioneros',  categoryLabel:'Camionero',  name:'Camionero Acero Liso',         variant:'Cuero Borravino',  details:['Camionero de Calabaza','Forrado en Cuero Liso Borravino','Virola de Acero Lisa'],      price:26500, image:'images/Camionero_Acero_Liso_Borravino.png',   featured:false },
  { id:11, category:'camioneros',  categoryLabel:'Camionero',  name:'Camionero Criollo',            variant:'',                 details:['Camionero Criollo de Calabaza','Base de Cuero'],                                       price:27000, image:'images/Camionero_Criollo.png',                 featured:false },
  { id:12, category:'camioneros',  categoryLabel:'Camionero',  name:'Camionero Algarrobo',          variant:'',                 details:['Camionero de Algarrobo','Virola de Acero Lisa'],                                       price:23500, image:'images/Camionero_Algarrobo.png',               featured:false },
  { id:13, category:'camioneros',  categoryLabel:'Camionero',  name:'Criollo con Virola',           variant:'',                 details:['Camionero Criollo de Calabaza','Base de Cuero','Virola de Acero Lisa'],                 price:29000, image:'images/Criollo_con_Virola.png',                featured:false },
  { id:14, category:'ranchero',    categoryLabel:'Ranchero',   name:'Ranchero Blanco',              variant:'',                 details:['Ranchero de Algarrobo','Color Blanco'],                                                price:32000, image:null,                                           featured:false },
  { id:15, category:'galleta',     categoryLabel:'Galleta',    name:'Mate Galleta',                 variant:'',                 details:['De Calabaza','Base de Cuero'],                                                         price:26000, image:null,                                           featured:false },
  { id:16, category:'materas',     categoryLabel:'Matera',     name:'Matera Simil Cuero',           variant:'Negra',            details:['Matera Simil Cuero Reforzada','Con Separador','Color Negra'],                          price:22500, image:'images/Matera_Simil_Cuero.png',                featured:false },
  { id:17, category:'materas',     categoryLabel:'Matera',     name:'Portamate Cuero',              variant:'Negro y Marron',   details:['Portamate 100% Cuero','Color Negro y Marron Claro'],                                   price:23000, image:'images/Portamate_Cuero.png',                   featured:false },
  { id:18, category:'bombillas',   categoryLabel:'Bombilla',   name:'Pico Loro Acero',              variant:'',                 details:['Bombilla Pico Loro','De Acero Inoxidable'],                                            price:8000,  image:'images/Pico_Loro_Acero.png',                   featured:false },
  { id:19, category:'bombillones', categoryLabel:'Bombillon',  name:'Pico Loro Premium',            variant:'',                 details:['Bombillon Pico Loro','De Alpaca y Bronce'],                                            price:35000, image:'images/Pico_Loro_Premium.png',                 featured:false },
  { id:20, category:'termos',      categoryLabel:'Termo',      name:'Termo Media Manija',           variant:'Color Negro',      details:['Termo de Acero','Color Negro'],                                                        price:26800, image:'images/Termo_Media_Manija.png',                featured:false }
];
